app: /home/henrydc/ILLIXR/.cache/paths/UnrealApp/UnrealAppTest/Binaries/Linux/UnrealAppTest
  # src_path:
#     git_repo : https://gitlab.freedesktop.org/monado/demos/openxr-simple-example
#     version  : master
#   bin_subpath: build/openxr-example
# config: {}
